[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules", "script/config"]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
    { access = "read", path = "./test/fixtures" },
]

[lint]
paths = ["src"]

[invariant]
runs = 256
depth = 10
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options